package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EtapaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtapaAllPropertiesEquals(Etapa expected, Etapa actual) {
        assertEtapaAutoGeneratedPropertiesEquals(expected, actual);
        assertEtapaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtapaAllUpdatablePropertiesEquals(Etapa expected, Etapa actual) {
        assertEtapaUpdatableFieldsEquals(expected, actual);
        assertEtapaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtapaAutoGeneratedPropertiesEquals(Etapa expected, Etapa actual) {
        assertThat(expected)
            .as("Verify Etapa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtapaUpdatableFieldsEquals(Etapa expected, Etapa actual) {
        assertThat(expected)
            .as("Verify Etapa relevant properties")
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getOrdem()).as("check ordem").isEqualTo(actual.getOrdem()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtapaUpdatableRelationshipsEquals(Etapa expected, Etapa actual) {
        assertThat(expected)
            .as("Verify Etapa relationships")
            .satisfies(e -> assertThat(e.getCompromisso()).as("check compromisso").isEqualTo(actual.getCompromisso()));
    }
}
